# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def for_test
  pod 'Quick'
  pod 'Nimble'
end 

target 'OpenMarket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenMarket

  target 'OpenMarketTests' do
    inherit! :search_paths
    # Pods for testing
    for_test
  end

  target 'OpenMarketUITests' do
    # Pods for testing
    for_test
  end

end
